#!/bin/bash

# Takes the basename of the test scrpt in /tests as an argument,
# any additional arguments if the test requires it, and runs the test.
#
# Usage: ./qa t1x chv-tat
#        ./qa testvoc reg

if [ $# -eq 0 ]
then
    testToRun=all.test
else
    testToRun=$1.test
fi

bash "tests/$testToRun" "$2" "$3"
